ZSH_THEME=powerlevel10k/powerlevel10k

export ZSH="$HOME/.oh-my-zsh"

plugins=(
    git
    zsh-autosuggestions
    dotenv
    macos
    npm
    zsh-syntax-highlighting
    docker
    docker-compose
    kubectl
    microk8s
    gcloud
    1password
    minikube
)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/noctifer20/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/noctifer20/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/noctifer20/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/noctifer20/google-cloud-sdk/completion.zsh.inc'; fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH=/Users/noctifer20/.local/bin:$PATH

